### ISSUE TITLE
[Error] v0.1.0 + v0.8.0 브랜치 병합 테스트 도커 컨테이너 다운

### ISSUE THREAD

**Issue by blahxblah** [oppenheimer-joa/movie-API#28]
안녕하세요. blahxblah 입니다.
v0.1.0 + v0.8.0 브랜치 병합 후 FastAPI 도커 테스트 중에 도컨 컨테이너 생성 즉시 종료가 됩니다.

- 오류 코드 : 
```bash
yoda@server01:~/sms/extract/tmpMerge2$ docker logs testapi-tmpMerge2
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from routers.test import router as test
  File "/api/routers/test.py", line 5, in <module>
    from utils.load_KOPIS import *
  File "/api/utils/load_KOPIS.py", line 11, in <module>
    SERVICE_KEY = config.get('KOPIS_KEYS', 'API_KEY')
  File "/usr/local/lib/python3.8/configparser.py", line 781, in get
    d = self._unify_values(section, vars)
  File "/usr/local/lib/python3.8/configparser.py", line 1149, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'KOPIS_KEYS'
```

config 경로의 config.ini 설정값의 문제라고 예상되지만 공통 config.ini 파일을 그대로 쓴거라 문제는 없어 보입니다.

**Comment by J3llyBe4n** [comment]
문제 해결 ---


config/config.ini 파일이 없는것으로 보입니다. 확인 해주시고 넣어서 빌드하시면 될 것 같습니다!
