### ISSUE TITLE
[MySQL] 데이터 적재 속도 관련 아이디어 브랜칭 보고서

### ISSUE THREAD

**Issue by hooniegit** [oppenheimer-joa/movie-API#54]
# 문제 상황
: 데이터베이스 업데이트 속도가 너무 느리다 (RDS가 프리티어임, 단일 스크립트로 실행, MySQL response 및 request response를 기반으로 데이터 적재)

# 검토
: 리소스 문제는 아님

# 초기 고안 해결 방안
1. insert many 수행
2. db connection pool 구성

**Comment by hooniegit** [comment]
# execute many 수행 결과
### 과정

``` python
QUERY = "INSERT INTO people(people_id, people_nm, date_gte) VALUES (%s, %s, %s)"
values = (id, original_name, date_gte)
try : 
    cursor.execute(QUERY, values)
    conn.commit()
except : print(f"Duplicated : {id}")
```

1. 중복 데이터 처리 방식 변경 (python : try&except > QUERY : INSERT IGNORE)
2. 

``` python
QUERY = "INSERT IGNORE INTO people(people_id, people_nm, date_gte) VALUES (%s, %s, %s)"
cursor.executemany(QUERY, value_list)
conn.commit()
```

### 결과
30 [line/sec] -> 100 [line/sec]

**Comment by hooniegit** [comment]
# db connection pool 수행 결과
### 과정

### 오류
```
Traceback (most recent call last):
  File "connection_pool.py", line 125, in <module>
    pool = pooling.MySQLConnectionPool(**dbconfig, **poolconfig)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/pooling.py", line 159, in __init__
    self.add_connection()
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/pooling.py", line 270, in add_connection
    cnx = MySQLConnection(**self._cnx_config)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 95, in __init__
    self.connect(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/abstracts.py", line 716, in connect
    self._open_connection()
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 208, in _open_connection
    self._do_auth(self._user, self._password,
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 144, in _do_auth
    self._auth_switch_request(username, password)
  File "/usr/local/lib/python3.8/dist-packages/mysql/connector/connection.py", line 177, in _auth_switch_request
    raise errors.get_exception(packet)
mysql.connector.errors.OperationalError: 1040 (08004): Too many connections
```
